INSERT INTO usuarios VALUES ("Alyssa Dillenburg Michalski", "alyssadillenburgm@gmail.com", "grupoajjjj")
INSERT INTO usuarios VALUES ("João Victor Freitas Batistela Trindade da Silva", "jv.trindadesilva@gmail.com", "grupoajjjj")
INSERT INTO usuarios VALUES ("João Vitor Angelo Pereira", "jvangelopereira@gmail.com", "grupoajjjj")
INSERT INTO usuarios VALUES ("Juan Álvaro Córdova", "juanalvaro067@gmail.com", "grupoajjjj")
INSERT INTO usuarios VALUES ("Júlia Conzatti", "juliarconzatti@gmail.com", "grupoajjjj")